### ISSUE TITLE
Use only MAC

### ISSUE THREAD

**Issue by xolom** [frankjoke/ioBroker.radar2#17]
Does this adapter allow to use also only the MAC ddress in combination with arp-scan, or is an IP necessary?
Because i can't get it to work without setting an IP address for each device.
I would like to use dynamic IP's and stick to the MAC address.

**Comment by xolom** [comment]
I think that arp-scan isn't working.. I can't find anything in the log output for the arp-scan call.How can i be sure, that arp is working? The thing is, that it looses connection to my mobile phone all the time and i think this is because it is only checkt by pinging the device

**Comment by frankjoke** [comment]
At first, please raise such questions in the forum: https://forum.iobroker.net/topic/19794/adapter-neuer-radar2-adapter, you can do it even in English if you do not speak German.

2) You alwas need an IP to get the mac address, Networks cannot send packets to mac address, only to IP.
You can use a name of dhe device instead of the ip, then the adapter will try to find IP from the name and then mac from IP.

If IP changes frequently you need to restart adrapter to get new IP address for the name! I automatically restart my adapter every day early in the morning so it can capture new addresses.
