### ISSUE TITLE
radar2, Version 2.x, Config lost/not visible

### ISSUE THREAD

**Issue by FRYYYYYY** [frankjoke/ioBroker.radar2#75]
Since the update to version 2.x, I am not able to see my config anymore. Radar2 adapter is working well, but I am not able to edit my config because it seems to be lost. When I downgrade to 1.2.5, I am able to see my config again, but the adapter is not working.

NPM 7.11.0
jscontroller 3.2.16

![image](https://user-images.githubusercontent.com/13643787/115919574-4e80e400-a479-11eb-873c-457d01b2720e.png)

Additionally, I tried to create a new instance, but I am not able to add entries; just nothing happens when I click it.

**Comment by BA2000** [comment]
Hi, i have the same problem. Delete, reinstall nothing helps.
NPM 7.10.0
NODE 14.16.1
jscontroller  3.2.16
System Ubuntu 20.04.2 LTS

If i load the old config, i can´t save the config, a message appears 'Would you leave, without save?' Yes or No?

Any ideas?

**Comment by jlegen** [comment]
> Any ideas?

are you already on admin 5.x? if yes, then downgrading to 4.2.1 could help...

**Comment by R-Guhr** [comment]
Hi, i have the same problem. Delete, reinstall nothing helps.

Node.js 12.22.1
NPM 6.14.12
js-controller 3.3.7
System Debian 10

If i load the old config, i can´t save the config, a message appears 'Would you leave, without save?' Yes or No?

Any ideas?

**Comment by darkman242** [comment]
You must use the Admin Adapter in version 4.2.1 as a workaround.

> Hi, i have the same problem. Delete, reinstall nothing helps.
> 
> Node.js 12.22.1
> NPM 6.14.12
> js-controller 3.3.7
> System Debian 10
> 
> If i load the old config, i can´t save the config, a message appears 'Would you leave, without save?' Yes or No?
> 
> Any ideas?

You must use the Admin Adapter in version 4.2.1 as a workaround.

**Comment by frankjoke** [comment]
Ok, I was just chatting with admin/js-controller makers because I had similar problems.

They just made admin 5.0.14 which resolved the problems with me (running on Windows with Node 14.21.x, npm 6.x, and js-controller 3.3.5). I am carefun installing new versions, I have one test system where I test every new adapter or js-controller before I install them on my development or prime systems. Therefore I see the impact of very new installations maybe a bit later...

Anyhow, new js-controllers will still bring up `Read-only state "radar2.0....` warnings which I will need to change in new release of adapter which will be maybe v2.2 or so because it will move to a new admin style and some changed functionalities as well. This will be defenitely not before end of the month because of current workload.

**Comment by FRYYYYYY** [comment]
Sorry but this is not working for me. 

js-controller 3.3.8
admin 5.0.14
radar 2.0.1
npm 7.11.2
nodejs 12.22.1

**Comment by coyote1** [comment]
Same here, still not working:

js-controller: 3.3.8
admin 5.0.15
radar 20.1
npm 6.14.12
nodejs 12.22.1

**Comment by Beliar-666** [comment]
When will this be fixed?
